services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "${PORT:-3002}:3000"
    environment:
      PORT: 3000
      HOST: 0.0.0.0
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - .:/app
      - /app/node_modules
