sonar.projectKey=LF-Calegari_lfc-admin-gui
sonar.organization=lf-calegari

sonar.sources=src
sonar.tests=tests

sonar.exclusions=identity/**,**/*.test.*,**/*.spec.*
sonar.test.inclusions=tests/**/*.{test,spec}.{ts,tsx}

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
